name: test-conda-env-py3
channels:
- conda-forge
- nodefaults
dependencies:
- numpy
- sympy
- pocl
- islpy
- pyopencl
- python=3.9
- python-symengine
#- pyfmmlib
- cython
- pyvkfft
- pytools
- pip
- pymbolic
- codepy
- modepy
- genpy
- colorama
- mako
- pyrsistent
- immutables
- pytest
- types-dataclasses

- matplotlib-base
- tikzplotlib

- git
- compilers
